name: Regression

on:
  push:
    branches: [ "master" ]

jobs:
  job1:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - name: Step 1- Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2- Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      #- name: Update Linux
      #  run: sudo apt-get update

      #- name: Install Chrome
      #  run: |
        #  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
         # sudo dpkg -i google-chrome-stable_current_amd64.deb
         # sudo apt-get -f install

      

      - name: Step 3- Have GitHub Actions build Maven Project
        run: mvn test

      - name: Set up timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H-%M-%SZ')"

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Regression-${{ steps.timestamp.outputs.timestamp }}
          path: target
